Re-organization: 1st Pass
pixijs/webdoc-template pull request #33
Opened 2023-12-11 21:24 UTC by bbazukun123

Resolves [ticket](https://github.com/orgs/pixijs/projects/2/views/4?pane=issue&itemId=47054621).

- `publish.js` is now compiled from `src/index.ts` and its logic has been splitter into individual modules in `src/utils` for better readability and iteratability.
- Iteratable scripts and styles are now compiled into a set of `main.js` and `main.css` to be loaded with the HTML pages. All the main source files are moved into `src/static`.
- Rollup is used here for the bundling. (`npm run build` and `npm run watch` are available to update these essential files for the docs generation)
- Does not include any changes to the output docs.

2023-12-13 09:05 UTC, achamas-playco requested changes
Looks good except lets just add the `.vscode` detail to `.gitignore` before merging pls.

2023-12-13 09:05 UTC, achamas-playco commented on .vscode/settings.json
Looks like we're missing ignoring `.vscode` folder in the repos `.gitignore`.

We don't want to check in these files, it could blow away someone's local vscode environment.

Could you please add it to `.gitignore`?
```
.vscode
```

2023-12-13 14:08 UTC, bbazukun123 commented on .vscode/settings.json
oh yes, sorry about this 🙈

2023-12-14 04:37 UTC, achamas-playco approved these changes
Great stuff!

2023-12-14 11:38 UTC, merged